spring:
  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true